name: Build and Deploy

on:
  workflow_dispatch: # Allow manual trigger
  # push:
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    if: github.actor == 'slurrps-mcgee'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Log in to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract versions from package.json
      id: version
      shell: bash
      run: |
        echo "Extracting package versions..."

        BACKEND_VERSION=$(node -p "require('./backend/package.json').version")
        echo "BACKEND_VERSION=$BACKEND_VERSION" >> $GITHUB_ENV
        echo "Backend version: $BACKEND_VERSION"

        FRONTEND_VERSION=$(node -p "require('./frontend/package.json').version")
        echo "FRONTEND_VERSION=$FRONTEND_VERSION" >> $GITHUB_ENV
        echo "Frontend version: $FRONTEND_VERSION"

    - name: Build and push Backend image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: ./backend/dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/steamstats-backend:${{ env.BACKEND_VERSION }}
          ${{ secrets.DOCKER_USERNAME }}/steamstats-backend:latest

    - name: Build and push Frontend image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: ./frontend/dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/steamstats-frontend:${{ env.FRONTEND_VERSION }}
          ${{ secrets.DOCKER_USERNAME }}/steamstats-frontend:latest